server:
  port: 8763
eureka:
  client:
    eureka-server-u-r-l-context: http://localhost:8761/eureka

spring:
  application:
    name: producer-server
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: scott
    password: tiger
  redis:
    host: localhost
    port: 6379

mybatis:
  mapper-locations: mapper/*.xml


